name: Test LigaBartar Custom Emoji

on:
  workflow_dispatch:

jobs:
  test-emoji:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Telegram library
        run: pip install python-telegram-bot==20.8

      - name: Test Custom Emoji
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          cat > test_emoji.py <<'PY'
          import os
          import asyncio
          from telegram import Bot

          BOT_TOKEN = os.environ["BOT_TOKEN"]
          CHANNEL_ID = os.environ["CHANNEL_ID"]

          CUSTOM_EMOJI_ID = "5791645007882495057"

          async def main():

              bot = Bot(
                  token=BOT_TOKEN
              )

              print("Testing Custom Emoji...")
              print("CUSTOM EMOJI ID:", CUSTOM_EMOJI_ID)

              message = await bot.send_message(
                  chat_id=CHANNEL_ID,
                  text=(
                      '<tg-emoji emoji-id="'
                      + CUSTOM_EMOJI_ID
                      + '">⚽️</tg-emoji> '
                      'تست نهایی لوگوی لیگ‌برتر'
                  ),
                  parse_mode="HTML"
              )

              print("MESSAGE SENT")
              print("MESSAGE ID:", message.message_id)

          asyncio.run(main())
          PY

          python test_emoji.p
