name: Inspect Telegram Emoji

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Telegram library
        run: pip install python-telegram-bot==20.8

      - name: Run python
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -c "import os; from telegram import Bot; import asyncio; bot=Bot(os.environ['BOT_TOKEN']); print(asyncio.run(bot.get_me()))
