name: Main Yamal

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: TEST
        run: |
          echo "================================"
          echo "MAIN YAMAL IS RUNNING"
          echo "================================"
          echo "DATE:"
          date
          echo "PYTHON:"
          python3 --version
          echo "================================"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Check bot.py
        run: |
          echo "================================"
          echo "CHECKING BOT FILE"
          echo "================================"

          pwd
          echo "FILES:"
          ls -la

          echo "BOT.PY:"
          ls -lh bot.py

          echo "PYTHON:"
          python3 --version

          echo "================================"
          echo "TEST FINISHED"
          echo "================================"
